name = "worker-typescript-template"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "npm ci && npm run build"
[build.upload]
format = "service-worker"
